apiVersion: v1
kind: Pod
metadata:
  name: gs2-box
  namespace: undergrad-ms
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  containers:
  - name: main
    image: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel
    imagePullPolicy: IfNotPresent
    command: ["bash", "-lc", "sleep infinity"]
    workingDir: /workspace
    resources:
      limits:
        cpu: "8"
        memory: "32Gi"
        ephemeral-storage: "50Gi"
        nvidia.com/gpu: 1
      requests:
        cpu: "4"
        memory: "24Gi"
        ephemeral-storage: "40Gi"
        nvidia.com/gpu: 1
    volumeMounts:
    - name: work
      mountPath: /workspace
  volumes:
  - name: work
    emptyDir:
      sizeLimit: "20Gi"
